language: go
go_import_path: "github.com/juju/simplekv"
go: 
  - "1.9"
  - "1.10"
before_install:
  - "go get github.com/rogpeppe/godeps"
install:
  - "go get -d github.com/juju/simplekv"
  - "godeps -u $GOPATH/src/github.com/juju/simplekv/dependencies.tsv"
script: go test ./...
services:
  - mongodb
  - postgresql
addons:
   postgresql: "9.5"
